### ISSUE TITLE
Error: Unable to connect to the Database Server.

### ISSUE THREAD

**Issue by DauHoangTai** [justinhartman/complete-php7-ecom-website#8]
I can connect databases and login. But when I access http://localhost:9000/complete-php7-ecom-website/admin/categories.php it return below error
![image](https://user-images.githubusercontent.com/54855855/158984836-47c23add-3de8-4eb5-b858-96ee704a6bfe.png)
![image](https://user-images.githubusercontent.com/54855855/158984877-3239def6-de44-4c87-bc1c-e43833ffdd41.png)

**Comment by justinhartman** [comment]
You have to update your `.env` file with the right credentials. Read through this properly https://github.com/justinhartman/complete-php7-ecom-website#installing-required-packages and you'll see you need to 
run `composer install` which will copy `config/.env.prod` to `config/.env`.

Remember that the `.env` file is a hidden file so you won't see it on Windows unless hidden files are enabled. Open this file up and then uncomment the database settings in your file so that it looks like this:

```env
export DB_HOSTNAME='localhost'
export DB_USERNAME='root'
export DB_PASSWORD='pass'
export DB_DATABASE='ecomphp'
export DB_PORT='3306'
```

All the details are in the README and you can reference it here https://github.com/justinhartman/complete-php7-ecom-website#update-config-variables too.

**Comment by justinhartman** [comment]
By the looks of your page you're probably also going to need to copy the supplied `.htaccess` file to your root folder. You can find the .htaccess file here `config/.htaccess.prod` and you need to copy it to your parent folder. 

On Linux you use the `cp` command to copy the file as follows:

```sh
/bin/cp config/.htaccess.prod .htaccess
```
